---
- name: Deploy a bunch of games to Kubernetes
  hosts: all
  gather_facts: true
  vars:
    ansible_python_interpreter: /usr/bin/python3

  roles:
    - role: roles/games/portal
    - role: roles/games/scribble

