---
galaxy_info:
  role_name: knative_eventing_receivers
  description: Create/upgrade a Knative Service receiver that can accept CloudEvents and print them to logs.
  min_ansible_version: "2.14"
  license: Apache-2.0
  platforms:
    - name: Ubuntu
      versions: ["jammy"]

dependencies: []

