---
galaxy_info:
  role_name: network_tools
  description: Install network tools (iw, speedtest-cli, curl)
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions: ["jammy"]
dependencies: []

