---
galaxy_info:
  role_name: knative_eventing_core
  description: Install/upgrade Knative Eventing core to latest stable and verify deployments are Available.
  min_ansible_version: "2.14"
  license: Apache-2.0
  platforms:
    - name: Ubuntu
      versions: ["jammy"]
dependencies: []

