---
galaxy_info:
  role_name: increase_file_limits
  description: Increase file descriptor limits via /etc/security/limits.d
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions: ["jammy"]
dependencies: []

