---
# REQUIRED: set privately
# kubectl_kubeconfig: /etc/kubernetes/admin.conf

games_namespace: games

portal_name: games-portal
portal_manifest_dir: "{{ ansible_env.HOME }}/k8s-manifests/games/portal"

portal_image: nginx:stable-alpine
portal_nodeport: 30083

# Define games here
portal_games:
  - name: "Scribble.rs"
    description: "Draw & guess party game"
    icon_text: "S"
    url: "http://192.168.86.24:30081/"

  - name: "Tetris"
    description: "Classic block stacking game"
    icon_text: "T"
    url: "http://192.168.86.24:30085/"

