---
kafka_user: kafka
kafka_group: kafka

kafka_version: "4.1.1"
kafka_scala_version: "2.13"

kafka_install_dir: "/opt/kafka"
kafka_data_dir: "/var/lib/kafka"
kafka_log_dir: "/var/log/kafka"

kafka_cleanup_old_versions: true
