---
- name: Ship server logs to Kafka
  hosts: all
  become: true
  gather_facts: true

  roles:
    - role: roles/tuning/srv_logs_to_kafka
      kafka_bootstrap_servers: "10.0.0.10:9092"
      kafka_topic: "server-daily-logs"

