---
galaxy_info:
  role_name: knative_serving_crds
  description: Install/upgrade Knative Serving CRDs to the latest stable release.
  min_ansible_version: "2.14"
  license: Apache-2.0
  platforms:
    - name: Ubuntu
      versions: ["jammy"]

dependencies: []

