---
- name: Install necessary tools
  hosts: all
  become: yes
  roles:
    - roles/os/packages/install_dev_tools
    - roles/os/packages/install_network_tools
    - roles/os/packages/install_security_tools
    - roles/networking/vpn/install_tailscale_vpn

