apiVersion: apps/v1
kind: Deployment
metadata:
  name: navidrome-deployment
  namespace: music
spec:
  replicas: 3
  selector:
    matchLabels:
      app: navidrome
  template:
    metadata:
      labels:
        app: navidrome
    spec:
      containers:
      - name: navidrome
        image: deluan/navidrome:latest
        ports:
          - containerPort: 4533
        env:
          - name: ND_MUSICFOLDER
            value: "/muzik"
          - name: ND_DATAFOLDER
            value: "/data"
        volumeMounts:
          - name: music-storage
            mountPath: "/muzik"
          - name: data-storage
            mountPath: "/data"
      volumes:
        - name: music-storage
          hostPath:
            path: /mnt/f/Muzik
            type: Directory
        - name: data-storage
          hostPath:
            path: /mnt/d/navidrome_data
            type: DirectoryOrCreate
