---
knative_kubeconfig_path: "/etc/kubernetes/admin.conf"

knative_eventing_github_latest_api: "https://api.github.com/repos/knative/eventing/releases/latest"
knative_eventing_mtcb_manifest_path: "/tmp/knative-eventing-mt-channel-broker.yaml"

knative_eventing_namespace: "knative-eventing"

knative_eventing_mtcb_deployments:
  - "mt-broker-controller"
  - "mt-broker-filter"
  - "mt-broker-ingress"

knative_eventing_mtcb_verify_retries: 60
knative_eventing_mtcb_verify_delay: 3

