---
galaxy_info:
  role_name: knative_net_kourier
  description: Install/upgrade Knative net-kourier (Kourier ingress) to the latest stable release and verify readiness.
  min_ansible_version: "2.14"
  license: Apache-2.0
  platforms:
    - name: Ubuntu
      versions: ["jammy"]

dependencies: []

