---
- name: Install and provision Kafka (KRaft)
  hosts: all
  become: true
  roles:
    - role: streaming/kafka/install
    - role: streaming/kafka/cluster_id
    - role: streaming/kafka/configure
    - role: streaming/kafka/verify
