apiVersion: v1
kind: Service
metadata:
  name: navidrome
  namespace: music
spec:
  type: NodePort
  selector:
    app: navidrome
  ports:
    - name: http
      port: 4533
      targetPort: 4533
      nodePort: 30453
