apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-navidrome-music
  namespace: music
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  volumeName: pv-navidrome-music
  resources:
    requests:
      storage: 2Ti
