apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-navidrome-music
spec:
  capacity:
    storage: 2Ti
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/external/Muzik
    type: Directory
