apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-navidrome-data
  namespace: music
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: pv-navidrome-data
  resources:
    requests:
      storage: 10Gi
