---
galaxy_info:
  role_name: knative_serving_ingressclass_kourier
  description: Configure Knative Serving config-network to use Kourier ingress-class by default.
  min_ansible_version: "2.14"
  license: Apache-2.0
  platforms:
    - name: Ubuntu
      versions: ["jammy"]

dependencies: []

