---
- name: Falco rules pipeline (end-to-end)
  hosts: all
  become: true
  gather_facts: true

  roles:
    - role: roles/security/ids/falco/discovery
    - role: roles/security/ids/falco/rules_source
    - role: rolessecurity/ids/falco/validate
    - role: roles/security/ids/falco/deploy
    - role: roles/security/ids/falco/reload
    - role: roles/security/ids/falco/report

